// vue-main/src/layouts/login/LoginComponent.vue
<template>
  <section class="login-container">
    <a-form class="login-form" :form="form" @submit="onClickSubmit">
      <a-form-item>
        <a-input v-decorator="['userName', {rules: [{required: true}]}]" placeholder="Username">
          <a-icon slot="prefix" type="user" />
        </a-input>
      </a-form-item>
      <a-form-item>
        <a-input v-decorator="['password', {rules: [{required: true}]}]" type="password" placeholder="Password">
          <a-icon slot="prefix" type="lock" />
        </a-input>
      </a-form-item>
      <a-form-item>
        <a-button type="primary" html-type="submit" class="login-form-button"> Login </a-button>
      </a-form-item>
    </a-form>
  </section>
</template>

<script>
import {mapActions} from 'vuex';
// apis
import {apiPostAuthLogin} from '@src/apis/auth';
// utils
// types
// stores
// configs
// components
export default {
  name: 'LoginComponent',
  components: {},
  computed: {},
  data() {
    const _this = this;

    return {
      form: _this.$form.createForm(_this),
    };
  },
  methods: {
    ...mapActions(['setUserinfo']),
    async onClickSubmit(e) {
      try {
        e.preventDefault();
        const _this = this;
        const values = await _this.form.validateFields();
        const {code, data} = await apiPostAuthLogin(values);
        if (code === '200') {
          await _this.setUserinfo(data);
          _this.$router.push({path: '/root'});
        }
      } catch (error) {
        console.error(error);
      }
    },
  },
};
</script>

<style lang="less" scoped>
.login-container {
  width: 400px;
  height: 300px;
  margin: 0 auto;
}
</style>

// cra-main/src/layouts/login/LoginComponent.tsx
/*
 * @Author: wdy
 * @Date: 2019-03-27 17:32:33
 * @Last Modified by: wdy
 * @Last Modified time: 2022-01-21 11:40:10
 * @des 主布局，多屏模式
 */
import styles from './LoginComponent.module.less';
import React from 'react';
import { useRequest } from 'ahooks';
import { Form, Input, Button } from 'antd';
// type
import type { FunctionComponent } from 'react';
import type { TypeAseitResponse, Props } from './types';
import type { TypeApiPostAuthLoginData } from '@src/apis/auth';
// config
// api
import { apiPostAuthLogin } from '@src/apis/auth';
// util
// store
// component
const LoginComponent: FunctionComponent<Props> = (props) => {
  const { loading, runAsync } = useRequest((values: TypeApiPostAuthLoginData) => apiPostAuthLogin(values), {
    manual: true,
    throttleWait: 300,
    onSuccess: async (result: TypeAseitResponse) => {
      const { code, data } = result;
      if (code === '200' && data) {
        await props.setUserInfo(data);
        await props.history.push({ pathname: '/root' });
      }
    }
  });

  const login = async (values: TypeApiPostAuthLoginData) => {
    try {
      runAsync(values);
    } catch (error) {}
  };

  const renderForm = () => (
    <Form layout={'horizontal'} onFinish={login}>
      <Form.Item label={'用户名'} name={'username'} labelCol={{ span: 6 }} wrapperCol={{ span: 16 }}>
        <Input placeholder={'用户名'} />
      </Form.Item>
      <Form.Item label={'密码'} name={'password'} labelCol={{ span: 6 }} wrapperCol={{ span: 16 }}>
        <Input.Password placeholder={'密码'} />
      </Form.Item>
      <Form.Item>
        <Button type={'primary'} loading={loading} block htmlType={'submit'}>
          登录
        </Button>
      </Form.Item>
    </Form>
  );
  return (
    <section className={styles['layouts']}>
      <section className={styles['form-content']}>{renderForm()}</section>
    </section>
  );
};

export default LoginComponent;
