// react-main/src/pages/base/employeeServerPermissions/index.tsx
import React from 'react'; import zhCN from 'antd/lib/locale/zh_CN'; import {ConfigProvider} from 'antd';
// apis
// hooks
// utils
// types
import type {Props} from './types.d';
import type {FunctionComponent} from 'react';
// stores
// configs
// components
import EmployeeServerPermissionsComponent from './EmployeeServerPermissionsComponent';
const EmployeeServerPermissions: FunctionComponent<Props> = props => (
  <ConfigProvider locale={zhCN} input={{autoComplete: 'off'}}>
    <EmployeeServerPermissionsComponent {...props} />
  </ConfigProvider>
);
// const mapStateToProps = (state: TypeStore) => ({...state});
// const mapDispatchToProps = (dispatch: Dispatch) => ({});
// export default connect(mapStateToProps, mapDispatchToProps)(EmployeeServerPermissions);
export default EmployeeServerPermissions;

// vue-main/src/pages/base/employeeServerPermissions/index.vue
<template>
  <a-config-provider :locale="locale">
    <EmployeeServerPermissionsComponent />
  </a-config-provider>
</template>
<script>
import zhCN from 'ant-design-vue/es/locale/zh_CN';
// apis
// utils
// types
// stores
// configs
// components
import EmployeeServerPermissionsComponent from './EmployeeServerPermissionsComponent';
export default {
  name: 'EmployeeServerPermissions',
  components: {EmployeeServerPermissionsComponent},
  computed: {
    locale() {
      return zhCN;
    },
  },
};
</script>
<style lang="less" scoped></style>
