// vue-main/src/layouts/login/LoginComponent.vue
<template>
  <section class="login-container">
    <a-form class="login-form" :form="form" @submit="onClickSubmit">
      <a-form-item>
        <a-input v-decorator="['userName', {rules: [{required: true}]}]" placeholder="Username">
          <a-icon slot="prefix" type="user" />
        </a-input>
      </a-form-item>
      <a-form-item>
        <a-input v-decorator="['password', {rules: [{required: true}]}]" type="password" placeholder="Password">
          <a-icon slot="prefix" type="lock" />
        </a-input>
      </a-form-item>
      <a-form-item>
        <a-button type="primary" html-type="submit" class="login-form-button"> Login </a-button>
      </a-form-item>
    </a-form>
  </section>
</template>

<script>
import {mapActions} from 'vuex';
// apis
import {apiPostAuthLogin} from '@src/apis/auth';
// utils
// types
// stores
// configs
// components
export default {
  name: 'LoginComponent',
  components: {},
  computed: {},
  data() {
    const _this = this;

    return {
      form: _this.$form.createForm(_this),
    };
  },
  methods: {
    ...mapActions(['setUserinfo']),
    async onClickSubmit(e) {
      try {
        e.preventDefault();
        const _this = this;
        const values = await _this.form.validateFields();
        const {code, data} = await apiPostAuthLogin(values);
        if (code === '200') {
          await _this.setUserinfo(data);
          _this.$router.push({path: '/root'});
        }
      } catch (error) {
        console.error(error);
      }
    },
  },
};
</script>

<style lang="less" scoped>
.login-container {
  width: 400px;
  height: 300px;
  margin: 0 auto;
}
</style>

// react-main/src/layouts/login/LoginComponent.tsx
/*
 * @Author: wdy
 * @Date: 2021-09-23 17:22:55
 * @Last Modified by: wdy
 * @Last Modified time: 2022-01-19 12:02:45
 */
import styles from './LoginComponent.module.less';
import React from 'react';
import {Form, Input, Button} from 'antd';
// apis
import {apiPostAuthLogin} from '@src/apis/auth';
// hooks
// utils
// types
import type {TypeHsRouteComponentProps} from '@src/types';
import type {FunctionComponent} from 'react';
// stores
// configs
// components
interface Props extends TypeHsRouteComponentProps {}
const LoginComponent: FunctionComponent<Props> = props => {
  const [form] = Form.useForm();

  const onClickLogin = async () => {
    try {
      const values = await form.validateFields();
      const {username, password} = values;
      const {code, data} = await apiPostAuthLogin({username, password});
      if (code === '200') {
        props.history.push({pathname: '/root'});
      }
    } catch (error) {}
  };
  return (
    <section className={styles['layouts']}>
      <section className={styles['form-content']}>
        <Form className={styles['form']} form={form} onFinish={onClickLogin}>
          <Form.Item
            className={styles['form-item']}
            label={'用户名'}
            name={'username'}
            labelCol={{span: 6}}
            wrapperCol={{span: 16}}
            rules={[{required: true}]}>
            <Input />
          </Form.Item>
          <Form.Item
            className={styles['form-item']}
            label={'密码'}
            name={'password'}
            labelCol={{span: 6}}
            wrapperCol={{span: 16}}
            rules={[{required: true}]}>
            <Input.Password />
          </Form.Item>
          <Form.Item className={styles['form-item']}>
            <Button type={'primary'} htmlType={'submit'} block>
              登录
            </Button>
          </Form.Item>
        </Form>
      </section>
    </section>
  );
};
export default LoginComponent;
