// vue-main/src/layouts/root/RootComponent.vue
<template>
  <a-layout class="main-layout">
    <a-layout-sider class="main-layout-sider" collapsible>
      <aside class="aside">
        <header class="header">
          <div class="logo" />
        </header>
        <section class="body">
          <a-menu mode="inline" @click="({key}) => onClickMenu(key)">
            <template v-for="menuItem in menuTree">
              <a-menu-item v-if="!menuItem.children" :key="menuItem.id" :title="menuItem.name"> {{ menuItem.name }}</a-menu-item>
              <a-sub-menu v-else :key="menuItem.id" :title="menuItem.name">
                <a-menu-item v-for="menu in menuItem.children" :key="menu.id" :title="menuItem.name">{{ menu.name }} </a-menu-item>
              </a-sub-menu>
            </template>
          </a-menu>
        </section>
      </aside>
    </a-layout-sider>
    <a-layout class="layout">
      <a-layout-header class="layout-header">Header</a-layout-header>
      <a-layout-content class="layout-content">
        <router-view />
      </a-layout-content>
      <a-layout-footer class="layout-footer">Footer</a-layout-footer>
    </a-layout>
  </a-layout>
</template>

<script>
import {isEmpty} from 'lodash';
import {mapGetters} from 'vuex';
// apis
import {apiGetAuthMenuTree} from '@src/apis/auth';
// utils
import {getTreeDataByKey} from '@src/utils';
// types
// stores
// configs
// components

export default {
  name: 'rootComponent',
  components: {},
  data() {
    return {
      menuTree: [], // 菜单树
    };
  },
  computed: {
    ...mapGetters(['userInfo']),
  },
  methods: {
    checkIsLogin() {
      try {
        const _this = this;
        const {userInfo} = this;
        // if (!userInfo.user_id) {
        //   _this.$router.replace({path: '/login'});
        // }
      } catch (error) {}
    },
    /**
     * 获取菜单树
     */
    async getAuthMenuTree() {
      try {
        const _this = this;
        const {code, data} = await apiGetAuthMenuTree();
        _this.$set(_this, 'menuTree', code === '200' && data?.length ? data : []);
      } catch (error) {}
    },
    /**
     * 点击指定菜单
     */
    onClickMenu(key) {
      try {
        const _this = this;
        const {menuTree} = _this;
        const selectMenu = getTreeDataByKey(menuTree, key, {keyKey: 'id', childrenKey: 'children'});
        const {route = {}} = selectMenu;

        console.error(key, selectMenu, route);
        if (!isEmpty(route)) {
          const {type, path = ''} = route;
          switch (type) {
            case 'self':
              _this.$router.push({path: `/root${path}`});
              break;
            case 'qiankun':
              window.history.pushState({}, '', `/root${path}`);
              break;
            default:
              break;
          }
        }
      } catch (error) {
        console.error(error);
      }
    },
  },
  created() {},
  mounted() {
    try {
      const _this = this;
      _this.$nextTick(() => {
        _this.checkIsLogin();
        _this.getAuthMenuTree();
      });
    } catch (error) {}
  },
  destroyed() {},
};
</script>

<style lang="less" scoped>
@import './RootComponent.less';
</style>

// react-main/src/layouts/root/RootComponent.tsx
/*
 * @Author: wdy
 * @Date: 2021-09-23 17:22:55
 * @Last Modified by: wdy
 * @Last Modified time: 2022-01-20 11:51:54
 */
import styles from './RootComponent.module.less';
import {isEmpty} from 'lodash';
import React, {Suspense} from 'react';
import {Switch} from 'react-router-dom';
import {Layout, Menu, Spin} from 'antd';
import {useRequest, useMount, useSafeState} from 'ahooks';
import {MailOutlined, CalendarOutlined} from '@ant-design/icons';
// apis
import {apiGetAuthMenuTree} from '@src/apis/auth';
// hooks
// utils
import {getTreeDataByKey} from '@src/utils';
// types
import type {FunctionComponent} from 'react';
import type {TypePageProps, TypeAseitResponse} from '@src/types';
import type {TypeMenu} from './types.d';
// stores
// configs
// components
import {HsdRoute} from '@src/components';
interface Props extends TypePageProps {}
const {SubMenu} = Menu;
const {Header, Content, Footer, Sider} = Layout;
const RootComponent: FunctionComponent<Props> = props => {
  const {routes = []} = props;
  const [menuTree, setMenuTree] = useSafeState<TypeMenu[]>([]);
  const {loading: loadingGetAuthMenuTree, runAsync} = useRequest(() => apiGetAuthMenuTree(), {
    manual: true,
    throttleWait: 300,
    onSuccess: (result: TypeAseitResponse) => {
      const {code, data} = result;
      setMenuTree(code === '200' && data?.length ? data : []);
    },
  });

  const onClickMenu = (key: string) => {
    try {
      const selectMenu: TypeMenu = getTreeDataByKey(menuTree, key, {keyKey: 'id', childrenKey: 'children'});
      const {route = {}} = selectMenu;
      if (!isEmpty(route)) {
        const {type, path = ''} = route;
        switch (type) {
          case 'self':
            props.history.push({pathname: `/root${path}`});
            break;
          case 'qiankun':
            props.history.push({pathname: `/root${path}`});
            // window.history.pushState({}, '', `/root${path}`);
            break;
          default:
            break;
        }
      }
    } catch (error) {}
  };
  useMount(runAsync);

  const renderMenu = (menuTree: TypeMenu[]) => {
    return menuTree.map((menuItem: TypeMenu) =>
      menuItem?.children?.length ? (
        <SubMenu key={menuItem.id} title={menuItem.name} icon={<MailOutlined />}>
          {renderMenu(menuItem.children || [])}
        </SubMenu>
      ) : (
        <Menu.Item key={menuItem.id} title={menuItem.name} icon={<CalendarOutlined />}>
          {menuItem.name}
        </Menu.Item>
      ),
    );
  };

  const renderAside = () => (
    <aside className={styles['aside']}>
      <header className={styles['header']}></header>
      <section className={styles['body']}>
        {loadingGetAuthMenuTree ? (
          <Spin className={styles['menu-tree-spin']} />
        ) : (
          <Menu
            mode={'inline'}
            onClick={({key}) => {
              onClickMenu(`${key}`);
            }}>
            {renderMenu(menuTree)}
          </Menu>
        )}
      </section>
    </aside>
  );
  return (
    <Layout className={styles['main-layout']}>
      <Sider className={styles['main-layout-sider']} width={300} collapsible>
        {renderAside()}
      </Sider>
      <Layout className={styles['layout']}>
        <Header className={styles['layout-header']} />
        <Content className={styles['layout-content']}>
          <Suspense fallback={<Spin className={styles['layout-content-spin']} />}>
            <Switch>
              {routes.map((route, i) => (
                <HsdRoute key={i} {...route} />
              ))}
            </Switch>
          </Suspense>
        </Content>
        <Footer className={styles['layout-footer']}>Ant Design ©2018 Created by Ant UED</Footer>
      </Layout>
    </Layout>
  );
};
export default RootComponent;
