// react-main/src/pages/base/roleMenuConfigs/RoleMenuConfigsComponent.tsx
import styles from './RoleMenuConfigsComponent.module.less';
import React from 'react';
import {useRequest} from 'ahooks';
import {Form, Input, Button} from 'antd';
// apis
// hooks
// utils
// types
import type {FunctionComponent} from 'react';
import type {TypePageProps, TypeAseitResponse} from '@src/types';
// stores
// configs
// components
interface InnerProps extends TypePageProps {}
const RoleMenuConfigsComponent: FunctionComponent<InnerProps> = props => {
  return <section className={styles['container']}>RoleMenuConfigsComponent</section>;
}
export default RoleMenuConfigsComponent;

// vue-main/src/pages/base/roleMenuConfigs/RoleMenuConfigsComponent.vue
<template>
  <section>RoleMenuConfigsComponent</section>
</template>
<script>
// apis
// utils
// types
// stores
// configs
// components
export default {
  name: 'RoleMenuConfigsComponent',
  components: {},
  data() {
    return {};
  },
  computed: {},
  methods: {},
  mounted() {
    const _this = this;
    _this.$nextTick(() => {});
  },
  destroyed() {},
};
</script>
<style lang="less" scoped></style>
